[theme]
primaryColor="#9a6cfc"  # Neon Violet
backgroundColor="#1c1c1c"  # Deep Black Background
secondaryBackgroundColor="#303030"  # Darker Gray for Secondary Background
textColor="#ffffff"  # Bright White Text
